token: ""
path: [/kale]
minerName: LokmanBey
apiKey: 0adabcb5-645d-45e4-a7f9-39fcedb47467
cachePath: ""
deviceId: ""
extraParams: {}
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  info: ""
  submit: ""
  line: ""
  ws: ""
scanPath: true
scanMinute: 60
debug: ""
language: cn
multithreadingLoad: false
